version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/nginx/html
permissions:
   - object: /usr/share/nginx/html
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file
